name: .NET Core CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
        source-url: https://nuget.pkg.github.com/starcraft66/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        source-url: https://nuget.pkg.github.com/starcraft66/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet pack --configuration Release /p:VersionPrefix=3.5.1
    - name: Push generated package to GitHub registry
      run: |
        dotnet nuget push ./Artifacts/Release/*.nupkg --api-key ${{ secrets.PAT }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate --no-symbols true